version: '3.1'
services:
    jenkins-host:
        container_name: jenkins-host
        ports:
            - '8082:8080'
            - '50000:50000'
        image: jenkins-host
        volumes:
            - test:/var/jenkins_home
#    jenkins-worker:
#        container_name: jenkins-worker
#        restart: always
#        environment:
#            - 'JENKINS_URL=http://jenkins:8080'
#        image: jenkins-worker
#        volumes:
#            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
#            - /home/jenkins:/home/jenkins # Avoid mysql volume mount issue
#        depends_on:
#            - jenkins-host
